server.port=8082
spring.application.name=ms-mascotas

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_mascotas
spring.datasource.username=postgres
spring.datasource.password=tu_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Registro en Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Seguridad (Misma clave que el Gateway y Auth)
jwt.secret=tu_clave_secreta_super_segura_de_32_caracteres