services:
  db-usuarios:
    image: postgres:15
    container_name: db-usuarios
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_usuarios
    ports:
      - "5433:5432"
    volumes:
      - vol-usuarios:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  db-mascotas:
    image: postgres:15
    container_name: db-mascotas
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_mascotas
    ports:
      - "5434:5432"
    volumes:
      - vol-mascotas:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  db-geolocalizacion:
    image: postgres:15
    container_name: db-geolocalizacion
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_geo
    ports:
      - "5435:5432"
    volumes:
      - vol-geo:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  db-coincidencias:
    image: postgres:15
    container_name: db-coincidencias
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_coincidencias
    ports:
      - "5436:5432"
    volumes:
      - vol-coincidencias:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  db-reportes:
    image: postgres:15
    container_name: db-reportes
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_reportes
    ports:
      - "5437:5432"
    volumes:
      - vol-reportes:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  rabbitmq-sanos:
    image: rabbitmq:3-management
    container_name: rabbitmq-sanos
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - sanosysalvos-net

  # --- INFRAESTRUCTURA DE SONARQUBE ---
  db-sonarqube:
    image: postgres:16-alpine
    container_name: db-sonarqube
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar_password_1234
      POSTGRES_DB: sonar
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - db-sonarqube
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar_password_1234
      SONAR_JDBC_URL: jdbc:postgresql://db-sonarqube:5432/sonar
    ports:
      - "9000:9000"
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-extensions:/opt/sonarqube/extensions
      - sonar-logs:/opt/sonarqube/logs
    networks:
      - sanosysalvos-net

networks:
  sanosysalvos-net:
    driver: bridge

volumes:
  vol-usuarios:
  vol-mascotas:
  vol-geo:
  vol-coincidencias:
  vol-reportes:
  sonar-db-data:
  sonar-data:
  sonar-extensions:
  sonar-logs: