server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Permite encontrar servicios en Eureka por su nombre
      routes:
        - id: ms-usuarios
          uri: lb://MS-USUARIOS # "lb" usa el Load Balancer de Eureka
          predicates:
            - Path=/api/usuarios/** # Todo lo que empiece así se va a Usuarios
        - id: ms-mascotas
          uri: lb://MS-MASCOTAS # Ruta para el servicio de mascotas
          predicates:
            - Path=/api/mascotas/** # Todo lo que empiece así se va a ms-mascotas
        - id: auth-service
          uri: lb://AUTH-SERVICE # Ruta para el servicio de autenticación
          predicates:
            - Path=/api/auth/** # Todo lo que empiece así se va al auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: SanosYSalvos_Super_Secret_Key_2026_Duoc_Technical_Project
