server.port=8083
spring.application.name=ms-geolocalizacion

spring.datasource.url=jdbc:postgresql://localhost:5435/db_geo
spring.datasource.username=user_sanos
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=ejemplo_clave_secreta_para_geo_1234567890
