server.port=8084
spring.application.name=ms-coincidencias

spring.datasource.url=jdbc:postgresql://localhost:5436/db_coincidencias
spring.datasource.username=user_sanos
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

jwt.secret=ms_coincidencias_secret_1234567890_abcdef
