version: '3.8'

services:
  db-usuarios:
    image: postgres:15
    container_name: db-usuarios
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_usuarios
    ports:
      - "5433:5432"
    volumes:
      - vol-usuarios:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  db-mascotas:
    image: postgres:15
    container_name: db-mascotas
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_mascotas
    ports:
      - "5434:5432"
    volumes:
      - vol-mascotas:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  db-geolocalizacion:
    image: postgres:15
    container_name: db-geolocalizacion
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_geo
    ports:
      - "5435:5432"
    volumes:
      - vol-geo:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

  db-coincidencias:
    image: postgres:15
    container_name: db-coincidencias
    environment:
      POSTGRES_USER: user_sanos
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_coincidencias
    ports:
      - "5436:5432"
    volumes:
      - vol-coincidencias:/var/lib/postgresql/data
    networks:
      - sanosysalvos-net

networks:
  sanosysalvos-net:
    driver: bridge

volumes:
  vol-usuarios:
  vol-mascotas:
  vol-geo:
  vol-coincidencias: